# Generated by Django 5.0.3 on 2024-03-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_8_delete_student_11_alter_student_10_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '7-класс', 'verbose_name_plural': '7-класс'},
        ),
        migrations.AlterModelOptions(
            name='student_10',
            options={'verbose_name': '10-Класс', 'verbose_name_plural': '10-Класс'},
        ),
        migrations.AlterModelOptions(
            name='student_8',
            options={'verbose_name': '8-Класс', 'verbose_name_plural': '8-Класс'},
        ),
        migrations.AlterModelOptions(
            name='student_9',
            options={'verbose_name': '9-Класс', 'verbose_name_plural': '9-Класс'},
        ),
    ]
