# Generated by Django 5.0.3 on 2024-03-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_options_alter_student_10_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_10',
        ),
        migrations.DeleteModel(
            name='Student_9',
        ),
    ]
