# Generated by Django 5.0.3 on 2024-03-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_10'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_10',
        ),
    ]
