# Generated by Django 5.0.3 on 2024-03-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_10'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Жалпы', 'verbose_name_plural': 'Жалпы'},
        ),
    ]
