# Generated by Django 5.0.3 on 2024-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_student_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_7',
        ),
        migrations.AlterModelOptions(
            name='student_7',
            options={'verbose_name': '7-класс', 'verbose_name_plural': '7-класс'},
        ),
    ]
