# Generated by Django 5.0.3 on 2024-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_student_student_7_alter_student_7_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Окуучунун толук аты жөнү')),
                ('image_path', models.ImageField(blank=True, upload_to='images', verbose_name='Окуучунун сүрөтү (3Х4 өлчөмүндө)')),
                ('gender', models.CharField(choices=[('эркек', 'Эркек'), ('кыз', 'Кыз')], default='эркек', max_length=120, null=True, verbose_name='Жынысы')),
                ('birth_day', models.CharField(max_length=120, verbose_name='Тууган күнү, айы, жылы')),
                ('class_of_year', models.CharField(choices=[('7-класс', '7-класс'), ('8-класс', '8-класс'), ('9-класс', '9-класс'), ('10-класс', '10-класс')], default='7-класс', max_length=120, null=True, verbose_name='Бүтүргөн классы')),
                ('region', models.CharField(max_length=120, verbose_name='Жашаган облусу, району, айылы')),
                ('phone_number_student', models.CharField(max_length=120, verbose_name='Окуучунун телефон номери')),
                ('name_of_dud_mum', models.CharField(max_length=120, verbose_name='Ата-энесинин аты-жөнү')),
                ('phone_of_dud_mum', models.CharField(max_length=120, verbose_name='Ата-энесинин байланыш номери')),
                ('name_guardian', models.CharField(max_length=120, verbose_name='Окуучуга жоопту кишинин толук аты-жөнү')),
                ('phone_guardian', models.CharField(max_length=120, verbose_name='Окуучуга жоопту кишинин номери')),
                ('whatsapp', models.CharField(max_length=120, verbose_name='Ар дайым байланышта болгон вотсап номери')),
                ('interesting_lesson', models.CharField(max_length=120, verbose_name='Кызыккан сабактары')),
                ('success', models.CharField(max_length=120, verbose_name='Ийгиликтери (олимпиада, сабактар, спорт, маданий ж.б.)')),
                ('hobbies', models.CharField(max_length=120, verbose_name='Өнөрлөрү (Жөндөмдүүлүктөрү)')),
                ('date_of_saving', models.DateTimeField(auto_now_add=True, verbose_name='Катталган датасы')),
            ],
            options={
                'verbose_name': 'Жалпы',
                'verbose_name_plural': 'Жалпы',
            },
        ),
        migrations.AlterModelOptions(
            name='student_7',
            options={'verbose_name': '7-Класс', 'verbose_name_plural': '7-Класс'},
        ),
    ]
