# Generated by Django 5.0.1 on 2024-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_student_id_alter_student_10_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lang',
            field=models.CharField(choices=[('Кыргыз тили', 'Кыргыз тили'), ('Орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AddField(
            model_name='student_10',
            name='lang',
            field=models.CharField(choices=[('Кыргыз тили', 'Кыргыз тили'), ('Орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AddField(
            model_name='student_7',
            name='lang',
            field=models.CharField(choices=[('Кыргыз тили', 'Кыргыз тили'), ('Орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AddField(
            model_name='student_8',
            name='lang',
            field=models.CharField(choices=[('Кыргыз тили', 'Кыргыз тили'), ('Орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AddField(
            model_name='student_9',
            name='lang',
            field=models.CharField(choices=[('Кыргыз тили', 'Кыргыз тили'), ('Орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
    ]
