# Generated by Django 5.0.1 on 2024-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_student_lang_student_10_lang_student_7_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lang',
            field=models.CharField(choices=[('кыргыз тили', 'Кыргыз тили'), ('орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AlterField(
            model_name='student_10',
            name='lang',
            field=models.CharField(choices=[('кыргыз тили', 'Кыргыз тили'), ('орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AlterField(
            model_name='student_7',
            name='lang',
            field=models.CharField(choices=[('кыргыз тили', 'Кыргыз тили'), ('орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AlterField(
            model_name='student_8',
            name='lang',
            field=models.CharField(choices=[('кыргыз тили', 'Кыргыз тили'), ('орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
        migrations.AlterField(
            model_name='student_9',
            name='lang',
            field=models.CharField(choices=[('кыргыз тили', 'Кыргыз тили'), ('орус тили', 'Орус тили')], default='Кыргыз тили', max_length=120, null=True, verbose_name='Сынакты кайсыл тилде тапшырасыз?'),
        ),
    ]
