# Generated by Django 5.0.1 on 2024-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_student_lang_alter_student_10_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False, verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Активация',
                'verbose_name_plural': 'Активация',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('эркек', 'Эркек'), ('кыз', 'Кыз')], default='эркек', max_length=120, null=True, verbose_name='Жынысы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Окуучунун сүрөтү (3Х4 өлчөмүндө)'),
        ),
    ]
