# Generated by Django 5.0.1 on 2024-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_active_alter_student_gender_alter_student_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(max_length=120, verbose_name='Тууган күнү, айы, жылы'),
        ),
    ]
