# Generated by Django 5.0.1 on 2024-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_student_10_birth_day_alter_student_7_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.CharField(max_length=120, verbose_name='Тууган күнү, айы, жылы'),
        ),
        migrations.AlterField(
            model_name='student_10',
            name='birth_day',
            field=models.CharField(max_length=120, verbose_name='Тууган күнү'),
        ),
        migrations.AlterField(
            model_name='student_7',
            name='birth_day',
            field=models.CharField(max_length=120, verbose_name='Тууган күнү, айы, жылы'),
        ),
        migrations.AlterField(
            model_name='student_8',
            name='birth_day',
            field=models.CharField(max_length=120, verbose_name='Тууган күнү'),
        ),
        migrations.AlterField(
            model_name='student_9',
            name='birth_day',
            field=models.CharField(max_length=120, verbose_name='Тууган күнү'),
        ),
    ]
